### ISSUE TITLE
Uncaught Exception with latest Build Commit 1ca1205

### ISSUE THREAD

**Issue by fred26** [StarCrossPortal/ghidracraft#59]
I have managed to build latest build, and experiencing issues when opening a project and can't continue.

![image](https://user-images.githubusercontent.com/25375439/137389623-0e043596-d1ae-4c5f-ae7d-05cfbbc4475c.png)

I also have this problem with Ghidracraft-Nightly-2021-10-10.

I will try to setup Eclipse and maybe debug.

I am using Windows 10 x64.

**Comment by Escapingbug** [comment]
This seems to be relating to something about GUI (flatLAF), especially about the scripting part. Are you opening a previous project (in fact, previous file) or a new one?

**Comment by ioo0s** [comment]
You can try the latest release version, it should fix the problem
